{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    " 3,8 "
  ],
  "script": [
    "py.test -v -rf --cov =. --cov-report = html"
  ],
  "install": [
    "pip install -r requisitos.txt"
  ]
}
